"""
Django settings for messaging project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
from .common import *

ALLOWED_HOSTS = []
CONTAINER_PORT = 8008


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'messages',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'pdb',
        'PORT': '5432',
    }
}

MESSAGE_CLUSTER = [{'ip': '192.168.3.0', 'port':8001}]
